{{- $root := . -}}
{{- range $realm := .Values.realms }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak-realm.fullname" $root }}-{{ $realm.name }}
  labels:
    {{- include "keycloak-realm.labels" $root | nindent 4 }}
type: Opaque
data:
  realm.json: {{ $realm.realm | toJson | b64enc }}
{{- end }}
